USE Btap2_QLDA

-- Các câu truy vấn đơn giản
-- Câu 1
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE PHONG = 'NC'

-- Câu 2
SELECT MANV, HONV, TENLOT, TENNV, PHAI
FROM NHANVIEN
WHERE MLUONG > 3000000

-- Câu 3
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN NHAN VIEN', PHONG
FROM NHANVIEN
WHERE MLUONG BETWEEN 2000000 AND 3000000

-- Câu 4
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN NHAN VIEN'
FROM NHANVIEN
WHERE DCHI LIKE'%TPHCM'

-- Câu 5
SELECT NGSINH, DCHI
FROM NHANVIEN
WHERE HONV ='Dinh' AND TENLOT='Ba' AND TENNV='Tien'

--Câu 6
SELECT TENTN
FROM THANNHAN
WHERE YEAR(GETDATE())-YEAR(NGSINH)<18 AND MANV ='001'

--Câu 7
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN NHAN VIEN'
FROM NHANVIEN
WHERE YEAR(GETDATE())-YEAR(NGSINH)>30 AND PHAI='NU'

-- Phép kết
-- Câu 8
SELECT TENPHG AS 'TEN PHONG', DIADIEM AS 'DIA DIEM'
FROM PHONGBAN PB, DIADIEM_PHG DD
WHERE PB.MAPHG = DD.MAPHG

-- Câu 9
SELECT MANV, HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN TRUONG PHONG', TENPHG AS 'TEN PHONG BAN'
FROM PHONGBAN PB, NHANVIEN NV
WHERE PB.TRPHG = NV.MANV

-- Câu 10
SELECT TENDA, MADA, DDIEM_DA, DA.MAPHG, TENPHG, PB.MAPHG, TRPHG,NGNC
FROM PHONGBAN PB, DEAN DA, DIADIEM_PHG DD
WHERE PB.MAPHG = DA.MAPHG AND PB.MAPHG = DD.MAPHG

-- Câu 11
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN NHAN VIEN', DCHI as 'DIA CHI'
FROM PHONGBAN PB, NHANVIEN NV
WHERE PB.MAPHG = NV.PHONG AND TENPHG = 'Nghien Cuu'

-- Câu 12
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN NHAN VIEN', TENTN AS 'TEN THAN NHAN'
FROM THANNHAN TN, NHANVIEN NV
WHERE NV.MANV=TN.MANV AND NV.PHAI = 'Nu'

-- Câu 13
SELECT NV.MANV, HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN NHAN VIEN'
FROM PHONGBAN PB, NHANVIEN NV, DEAN DA, PHANCONG PC
WHERE PB.MAPHG=NV.PHONG AND PB.MAPHG=DA.MAPHG AND DA.MADA=PC.MADA AND PC.MANV=NV.MANV AND TENPHG='Nghien Cuu' AND TENDA LIKE 'Tin hoc hoa%' AND THOIGIAN =20

-- Câu 14
SELECT DA.MADA, DA.MAPHG AS 'MA PHONG', HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN TRUONG PHONG', DCHI AS 'DIA CHI', NGSINH AS 'NGAY SINH'
FROM PHONGBAN PB, NHANVIEN NV, DEAN DA, PHANCONG PC
WHERE PB.MAPHG = DA.MAPHG AND DA.MADA = PC.MADA AND PC.MANV = PB.TRPHG AND PB.TRPHG = NV.MANV AND DDIEM_DA ='HANOI'

-- Câu 15
SELECT NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV AS 'Họ Và Tên NV',QL.HONV+ ' ' +QL.TENLOT+ ' ' +QL.TENNV as 'Họ Và Tên Quản Lí'
FROM NHANVIEN NV,NHANVIEN QL
WHERE NV.MA_NQL=ql.MANV

-- Câu 16
SELECT NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV AS 'Họ Và Tên NV',
TP.HONV + ' ' + TP.TENLOT + ' ' + TP.TENNV AS 'Họ Và Tên Trưởng Phòng'
FROM NHANVIEN NV,NHANVIEN TP , PHONGBAN PD
WHERE   TP.MANV= PD.TRPHG and PD.MAPHG=NV.PHONG

-- Câu 17
SELECT HONV, TENLOT, TENNV, TENDA
FROM NHANVIEN NV, PHANCONG PC, DEAN D
WHERE NV.MA_NQL = PC.MANV AND PC.MADA LIKE D.MADA

-- Gom nhóm
-- Câu 18
SELECT DA.MADA, TENDA, SUM(THOIGIAN) AS 'TONG SO GIO LAM'
FROM DEAN DA, PHANCONG PC, NHANVIEN NV
WHERE NV.MANV = PC.MANV AND PC.MADA = DA.MADA
GROUP BY DA.MADA,TENDA

-- Câu 19
SELECT NV.MANV, HONV + ' ' + TENLOT + ' ' + TENNV AS 'HO TEN NHAN VIEN', COUNT(MATN) AS 'TONG SO THAN NHAN'
FROM NHANVIEN NV, THANNHAN TN
WHERE NV.MANV = TN.MANV
GROUP BY NV.MANV, HONV, TENLOT, TENNV

-- Câu 20
SELECT MAPHG TENPHG, AVG(NV.MLUONG) AS 'Lương trung bình'
FROM NHANVIEN NV, PHONGBAN PB
WHERE NV.PHONG = PB.MAPHG
GROUP BY MAPHG, TENPHG

-- Câu 21
SELECT MANV, TENNV , AVG(MLUONG) 'Lương trung bình'
FROM NHANVIEN
WHERE PHAI = 'Nu'
GROUP BY MANV, TENNV

-- Câu 22
SELECT TENPHG,COUNT(*) AS 'Số lượng nhân viên làm việc'
FROM PHONGBAN,NHANVIEN
WHERE MAPHG=PHONG
GROUP BY TENPHG
HAVING AVG(MLUONG)>30000

-- Câu truy vấn lồng
-- Câu 23
SELECT * FROM DEAN DA
WHERE DA.MADA IN (  
    SELECT PC.MADA FROM PHANCONG PC, NHANVIEN NV
    WHERE NV.HONV = 'Dinh' AND NV.MANV = PC.MANV 
) OR DA.MADA IN (
    SELECT DA.MADA FROM NHANVIEN NV, PHONGBAN PB
    WHERE NV.HONV = 'Dinh' AND PB.TRPHG = NV.MANV AND PB.MAPHG = DA.MAPHG 
)

-- Câu 24
SELECT Concat(NV.HONV, ' ', NV.TENLOT, ' ', NV.TENNV) N'Họ và tên' 
FROM NHANVIEN NV, (SELECT TN.MANV, COUNT(*) 'count' FROM THANNHAN TN GROUP BY TN.MANV) TEMP
WHERE NV.MANV = TEMP.MANV AND TEMP.count >= 2

-- Câu 25
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'DANH SACH NHAN VIEN KHONG CO THAN NHAN'
FROM NHANVIEN NV
WHERE NV.MANV NOT IN (
    SELECT TN.MANV
    FROM THANNHAN TN
    WHERE NV.MANV = TN.MANV
)

-- Câu 26
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'DANH SACH TRUONG PHONG CO TOI THIEU 1 THAN NHAN'
FROM NHANVIEN NV, PHONGBAN PB
WHERE NV.MANV = PB.TRPHG
AND (
    SELECT COUNT(*) FROM THANNHAN TN
    WHERE TN.MANV = NV.MANV
) >= 1

-- Câu 27
SELECT HONV, TENLOT, TENNV
FROM NHANVIEN NV, PHONGBAN PB
WHERE NV.MANV = PB.TRPHG AND
PB.TRPHG NOT IN (
    SELECT PB.TRPHG FROM PHONGBAN PB, THANNHAN TN
    WHERE PB.TRPHG = TN.MANV AND TN.QUANHE = N'Vo Chong'
)

-- Câu 28
SELECT HONV, TENLOT, TENNV 
FROM NHANVIEN NV
WHERE NV.MLUONG > (
    SELECT AVG(MLUONG) FROM NHANVIEN NV, PHONGBAN PB
    WHERE NV.PHONG=PB.MAPHG AND PB.TENPHG='Nghien cuu'
)

-- Câu 29
SELECT PB.TENPHG, (NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV) AS 'Họ tên trưởng phòng của phòng ban đông nhân viên nhất'
FROM NHANVIEN NV, PHONGBAN PB
WHERE NV.MANV = PB.TRPHG AND
PB.MAPHG IN (
    SELECT TOP(1) PB.MAPHG FROM NHANVIEN NV, PHONGBAN PB
    WHERE NV.PHONG = PB.MAPHG
    GROUP BY PB.MAPHG
    ORDER BY COUNT(*) DESC
)

-- câu 30
SELECT DISTINCT (NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV) AS 'Họ tên nhân viên', NV.DCHI
FROM NHANVIEN NV, DEAN DA, DIADIEM_PHG DD
WHERE NV.PHONG = DA.MAPHG AND
		NV.PHONG = DD.MAPHG AND
		DA.DDIEM_DA LIKE '%HCM' AND
		DD.DIADIEM NOT LIKE '%HCM'

-- Câu 31
SELECT DISTINCT (NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV) AS 'Họ tên nhân viên', NV.DCHI
FROM NHANVIEN NV, DEAN DA, DIADIEM_PHG DD
WHERE NV.PHONG = DA.MAPHG
AND NV.PHONG = DD.MAPHG
AND DD.DIADIEM NOT LIKE DA.DDIEM_DA
AND DA.DDIEM_DA IN (
    SELECT DA.DDIEM_DA FROM DEAN DA 
    ) 

-- Phép chia
-- Câu 32
SELECT nv1.MANV N'Mã nhân viên', Concat(nv1.HONV, ' ', nv1.TENLOT, ' ', nv1.TENNV) N'Họ và tên' FROM NHANVIEN nv1
WHERE nv1.MANV IN (
    SELECT PC1.MANV FROM PHANCONG PC1
    WHERE NOT EXISTS (
        SELECT * FROM DEAN DA
        WHERE NOT EXISTS (
            SELECT * FROM PHANCONG PC2
            WHERE PC2.MANV = PC1.MANV AND PC2.MADA = DA.MADA
        )
    )
)

-- Câu 33
SELECT nv1.MANV N'Mã nhân viên', Concat(nv1.HONV, ' ', nv1.TENLOT, ' ', nv1.TENNV) N'Họ và tên' FROM NHANVIEN nv1
WHERE nv1.MANV IN (
    SELECT PC1.MANV FROM PHANCONG PC1
    WHERE NOT EXISTS (
        SELECT * FROM DEAN DA, PHONGBAN PB
        WHERE PB.TENPHG = 'Nghien cuu' AND PB.MAPHG = DA.MAPHG AND NOT EXISTS (
            SELECT * FROM PHANCONG PC2
            WHERE PC2.MANV = PC1.MANV AND PC2.MADA = DA.MADA
        )
    )
)

-- Câu 34
-- Để test và ra được kết quả thì ta thêm vào 2 dòng trong PHANCONG như sau
INSERT PHANCONG VALUES ('003', 'DT001', 12.5)
INSERT PHANCONG VALUES ('003', 'DT002', 12.5)

SELECT nv1.MANV N'Mã nhân viên', Concat(nv1.HONV, ' ', nv1.TENLOT, ' ', nv1.TENNV) N'Họ và tên' FROM NHANVIEN nv1
WHERE nv1.MANV IN (
    SELECT PC1.MANV FROM PHANCONG PC1
    WHERE NOT EXISTS (
        SELECT * FROM DEAN DA, PHONGBAN PB
        WHERE PB.MAPHG = nv1.PHONG AND PB.MAPHG = DA.MAPHG AND NOT EXISTS (
            SELECT * FROM PHANCONG PC2
            WHERE PC2.MANV = PC1.MANV AND PC2.MADA = DA.MADA
        )
    )
)