USE QLSV_Lenh
GO
-- Làm bài tập tại đây
-- Câu 1
SELECT * FROM SVIEN
WHERE MAKHOA = 'TOAN'

-- Câu 2
SELECT TENMH, TINCHI
FROM MHOC

-- Câu 3
SELECT MASV, DIEM
FROM KQUA
WHERE MASV = 'K26.008'

-- Câu 4
SELECT SV.TENSV, MAMH, DIEM
FROM SVIEN SV JOIN KQUA KQ ON SV.MASV = KQ.MASV ,MHOC
WHERE KQ.DIEM > 7 AND MHOC.MAKHOA = SV.MAKHOA

-- Câu 5
SELECT TENSV
FROM SVIEN SV, MHOC MH
WHERE TENMH = 'Toan roi rac' AND SV.MAKHOA = MH.MAKHOA

-- Câu 6
SELECT TENSV, TENMH, DIEM
FROM KQUA KQ, SVIEN SV, HPHAN HP, MHOC MH
WHERE HP.HOCKY = 1 AND HP.NAM = 1996 AND SV.MASV = KQ.MASV AND KQ.MAHP = HP.MAHP AND HP.MAMH = MH.MAMH

-- Câu 7
SELECT TENMH 
FROM MHOC
WHERE MAMH IN (
    SELECT DK.MAMH_TRUOC
    FROM DKIEN DK JOIN MHOC MH ON DK.MAMH = MH.MAMH
    WHERE MH.TENMH LIKE 'Co so du lieu'
)

-- Câu 8
SELECT MH2.TENMH
FROM MHOC MH1, MHOC MH2, DKIEN
WHERE MH1.TENMH = 'Co so du lieu' AND MH1.MAMH = DKIEN.MAMH_TRUOC AND DKIEN.MAMH = MH2.MAMH

-- Câu 9
SELECT TENMH 
FROM MHOC MH, DKIEN DK
WHERE MH.MAMH = DK.MAMH_TRUOC AND MH.MAMH IN (
    SELECT DK.MAMH_TRUOC FROM MHOC, DKIEN
    WHERE MH.TINCHI <= 4 AND DK.MAMH = MH.MAMH
)

-- Câu 10
SELECT SV.* , DIEM 
FROM SVIEN SV, KQUA KQ, MHOC MH, HPHAN HP
WHERE SV.MASV = KQ.MASV AND KQ.MAHP = HP.MAHP AND HP.MAMH = MH.MAMH 
AND TENMH = 'Co so du lieu' 
AND HOCKY = 1 AND HP.NAM = 1996
ORDER BY DIEM DESC

-- Câu 11
SELECT MAHP, COUNT(MASV) SOLUONGSV
FROM KQUA
GROUP BY MAHP

-- Câu 12
SELECT SV.TENSV, AVG(DIEM) DIEMAVG, HP.HOCKY, HP.NAM
FROM SVIEN SV JOIN KQUA KQ ON SV.MASV = KQ.MASV, HPHAN HP
GROUP BY TENSV, HP.HOCKY, HP.NAM

-- Câu 13
SELECT TOP(1) WITH TIES TENSV, DIEM
FROM SVIEN SV JOIN KQUA KQ ON SV.MASV = KQ.MASV 
ORDER BY DIEM DESC

-- Câu 14
SELECT TOP(1) WITH TIES TENSV, DIEM
FROM SVIEN SV JOIN KQUA KQ ON SV.MASV = KQ.MASV JOIN HPHAN HP ON HP.MAHP = KQ.MAHP 
JOIN MHOC MH ON HP.MAMH = MH.MAMH
AND TENMH = 'Co so du lieu' 
AND HOCKY = 1 AND HP.NAM = 1996
ORDER BY DIEM DESC

-- Câu 15
SELECT TENSV, AVG(DIEM) DTB
FROM HPHAN HP, SVIEN SV, KQUA KQ, MHOC MH
WHERE HP.HOCKY = 1 AND HP.NAM = 1996 AND HP.MAMH = MH.MAMH AND HP.MAHP = KQ.MAHP AND KQ.MASV = SV.MASV
GROUP BY SV.MASV, TENSV
HAVING AVG(DIEM) > ALL (SELECT AVG(DIEM) FROM KQUA)

-- Câu 16
SELECT TOP(10) WITH TIES TENSV, DIEM
FROM SVIEN SV JOIN KQUA KQ ON SV.MASV = KQ.MASV JOIN HPHAN HP ON HP.MAHP = KQ.MAHP 
JOIN MHOC MH ON HP.MAMH = MH.MAMH
AND TENMH = 'Co so du lieu' AND HOCKY = 1 AND HP.NAM = 1996
ORDER BY DIEM DESC

-- Câu 17
SELECT MASV, TENSV 
FROM SVIEN
WHERE MASV NOT IN (
    SELECT MASV
    FROM KQUA KQ, HPHAN HP , MHOC MH
    WHERE KQ.MAHP = HP.MAHP AND HP.MAMH = MH.MAMH AND TENMH = 'Toan roi rac'
)

-- Câu 18
SELECT * FROM MHOC MH
WHERE MH.MAKHOA like 'TOAN' AND MH.MAMH NOT IN (
    SELECT HP.MAMH FROM HPHAN HP
    WHERE HP.HOCKY = 1 AND HP.NAM = 1996
    AND HP.MAMH = MH.MAMH
)

-- Câu 19
SELECT * FROM SVIEN SV
WHERE SV.MAKHOA = 'TOAN'
AND SV.NAM = 3
AND SV.MASV NOT IN (
    SELECT SV.MASV FROM KQUA KQ, HPHAN HP, MHOC MH
    WHERE MH.TENMH like 'Cơ sở dữ liệu' 
    AND HP.HOCKY = 1 AND HP.NAM = 1996
    AND MH.MAMH = HP.MAMH
    AND HP.MAHP = KQ.MAHP
    AND KQ.MASV = SV.MASV
)

-- Câu 20
SELECT * FROM SVIEN SV ,(
    SELECT KQ.MASV 'MASV', COUNT(*) 'COUNT' FROM KQUA KQ, HPHAN hp
    WHERE HP.HOCKY = 1 AND HP.NAM = 1996
    AND HP.MAHP = KQ.MAHP
    GROUP BY KQ.MASV
) tb2
WHERE tb2.COUNT >= 3 AND SV.MASV = tb2.MASV
