-- Cách 1: DÙNG ALTER(FOR)
CREATE TRIGGER tg_KQ_Sua_AfterFor ON dbo.KET_QUA
FOR UPDATE
AS
	BEGIN	
		DECLARE @MaSinhVien VARCHAR(20), @MaMonHoc VARCHAR(20), @Diem INT
			
	END
GO

-- Cách 2: DÙNG INSTEAD OF
CREATE TRIGGER tg_KQ_Sua_InsteadOf ON dbo.KET_QUA
INSTEAD OF UPDATE
AS
	BEGIN
	END
GO


