name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2022-09-28
version: '9.4.7'
project: 'drupal'
datestamp: 1664383388
